<?php namespace ProcessWire;
/*
This is a sendbox vertion.
If you wan use live rember to change the URL in access_token() and  client_token();

PayPal documentatio start here:
https://developer.paypal.com/docs/platforms/
*/

class PaymentPayPalCommercePlatform extends PaymentModule {

	public static function getModuleInfo() {
		return array('title'=> 'PayPal Commerce Platform',
			'summary'=> 'PayPal Commerce Platform - server side, credit card, paypal',
			'author'=> 'Marco Romano',
			'version'=> '0.1',
			'singular'=> false,
			'autoload'=> true,
			'requires'=> 'PaymentModule',
		);
	}

	public function init() {
		require_once dirname(wire('modules')->getModuleFile('PadCart')) . '/PadOrderProcess.php';
	}

	public function getTitle() {
		return __("All Payment method");
	}

	public function access_token() {
		if ($this->enviroment=="sandbox") {
			$clientId = $this->clientIdSandbox;
			$secret = $this->secretCodeSandbox;
			$url = 'https://api.sandbox.paypal.com/';
		} else {
			$clientId = $this->clientIdLive;
			$secret = $this->secretCodeLive;
			$url = 'https://api-m.paypal.com/';
		}

		$curl=curl_init();


		curl_setopt_array($curl, array(CURLOPT_URL=> $url."v1/oauth2/token", // Change URL for live
			CURLOPT_RETURNTRANSFER=> true,
			CURLOPT_SSL_VERIFYHOST=> false,
			CURLOPT_SSL_VERIFYPEER=> false,
			CURLOPT_CUSTOMREQUEST=> "POST",
			CURLOPT_POSTFIELDS=> "grant_type=client_credentials",
			CURLOPT_USERPWD=> $clientId .":". $secret,
			CURLOPT_HEADER=> false,
			CURLOPT_HTTPHEADER=> array("Accept: application/json",
				"Accept-Language: en_US",
			),
		));

		$response=curl_exec($curl);
		$err=curl_error($curl);

		$response=json_decode($response);
		$access_token=$response->access_token;
		return $access_token;
	}

	public function client_token() {
		if ($this->enviroment=="sandbox") {
			$url = 'https://api.sandbox.paypal.com/';
		} else {
			$url = 'https://api-m.paypal.com/';
		}

		$curl2=curl_init();
		curl_setopt_array($curl2, array(CURLOPT_URL=> $url."v1/identity/generate-token", // Change URL for live
			CURLOPT_RETURNTRANSFER=> true,
			CURLOPT_SSL_VERIFYHOST=> false,
			CURLOPT_SSL_VERIFYPEER=> false,
			CURLOPT_CUSTOMREQUEST=> "POST",
			CURLOPT_HEADER=> false,
			CURLOPT_HTTPHEADER=> array("Accept: application/json",
				"Accept-Language: en_US",
				"Authorization: Bearer ". $this->access_token(),
			),
		));
		$response=curl_exec($curl2);
		$err=curl_error($curl2);

		curl_close($curl2);
		$response=json_decode($response);
		$client_token=$response->client_token;
		return $client_token;
	}

	private function totalAmont(){
		$order_id = $this->id;
		$order = $this->getOrder($order_id);

		$totale = str_replace(",", ".", $order->pad_price_total);

		// $discountCode = $this->sanitizer->selectorValue($order->pad_discount_code);
		// $dc = $this->pages->get("template=paddiscount, title=$discountCode");

		$country = $order->pad_countrycode;
		$userBiz = $order->invoice_IVA_VAT;

		$cardDiscount = $order->CurrentAmount;

		// if (!empty($cardDiscount)) {
		// 	//$cardDiscount = str_replace('.', '', $cardDiscount);
		// 	$totale = $totale - $cardDiscount;
		// }

		if ($country == 'GB' && $totale < 155) {
			if ($userBiz) {
				$totale = $totale;
			} else {
				$scorporoIva = $totale * 1.20;
				$totale = floor(($scorporoIva*100))/100;
			}
		}

		return number_format($totale, 2);

	}

	public function render() {

		if ($this->enviroment=="sandbox") {
			$client_ID = $this->clientIdSandbox;
			$url = 'https://api.sandbox.paypal.com/';
		} else {
			$client_ID = $this->clientIdLive;
			$url = 'https://api-m.paypal.com/';
		}

		// original CSS
		echo "<style>
			/*
				.form-container {
					display: flex;
					background-color: #EEE;
					justify-content: center;
					align-items: center;
					height: 100%;
					flex-direction: column;
					border: 1em solid #fff;
					box-sizing: border-box;
					position: relative;
				}
			*/
			@media (max-width: 476px) {
				.form-container {
					border: none;
				}
			}
			.cardinfo-wrapper {
				display: flex;
				justify-content: space-around;
			}
			.card-shape,
			#card-form.visa,
			#card-form.master-card,
			#card-form.maestro,
			#card-form.american-express,
			#card-form.discover,
			#card-form.unionpay,
			#card-form.jcb,
			#card-form.diners-club {
				border-radius: 6px;
				padding: 1rem;
			}

			@media (max-width: 476px) {
				.card-shape,
				#card-form.visa,
				#card-form.master-card,
				#card-form.maestro,
				#card-form.american-express,
				#card-form.discover,
				#card-form.unionpay,
				#card-form.jcb,
				#card-form.diners-club {
					padding: 1rem;
				}
			}
			#pp-container {
				background-color: #FFF;
				box-shadow: 0 2px 4px rgba(0, 0, 0, 0.12);
				padding: 1rem;
				width: 20em;
				margin-bottom: 2em;
				transition: all 600ms cubic-bezier(0.2, 1.3, 0.7, 1);
				-webkit-animation: cardIntro 500ms cubic-bezier(0.2, 1.3, 0.7, 1);
				animation: cardIntro 500ms cubic-bezier(0.2, 1.3, 0.7, 1);
				z-index: 1;
			}
			.pp-container{
				display:inline-block;
				width:100%;
			}
			#card-form {
				display:inline-block;
				background-color: #FFF;
				box-shadow: 0px 3px 10px rgb(0 0 0 / 12%);
				padding: 1rem;
				margin-bottom: 2em;
				transition: all 600ms cubic-bezier(0.2, 1.3, 0.7, 1);
				-webkit-animation: cardIntro 500ms cubic-bezier(0.2, 1.3, 0.7, 1);
				animation: cardIntro 500ms cubic-bezier(0.2, 1.3, 0.7, 1);
				z-index: 1;
			}
			#card-form:hover {
				box-shadow: 0 4px 8px rgba(0, 0, 0, 0.06);
			}
			@media (max-width: 476px) {
				#card-form {
					box-sizing: border-box;
					padding: 1rem;
					width: 100%;
				}
			}
			#card-form.visa {
				color: #fff;
				background-color: #0D4AA2;
			}
			#card-form.master-card {
				color: #fff;
				background-color: #363636;
				background: linear-gradient(115deg, #d82332, #d82332 50%, #f1ad3d 50%, #f1ad3d);
			}
			#card-form.maestro {
				color: #fff;
				background-color: #363636;
				background: linear-gradient(115deg, #009ddd, #009ddd 50%, #ed1c2e 50%, #ed1c2e);
			}
			#card-form.american-express {
				color: #fff;
				background-color: #007CC3;
			}
			#card-form.discover {
				color: #fff;
				background-color: #ff6000;
				background: linear-gradient(#d14310, #f7961e);
			}
			#card-form.unionpay,
			#card-form.jcb,
			#card-form.diners-club {
				color: #fff;
				background-color: #363636;
			}
			.cardinfo-label {
				display: block;
				font-size: 11px;
				margin-bottom: 0.5em;
				text-transform: uppercase;
			}
			.cardinfo-exp-date {
				margin-right: 1em;
				width: 100%;
			}
			.cardinfo-cvv {
				width: 100%;
			}
			#button-pay {
				display:block;
				width:100%;
				cursor: pointer;
				font-size: 15px;
				border: 0;
				padding: 1.2em 1em;
				color: #fff;
				background: #282c37;
				border-radius: 4px;
				z-index: 0;
				-webkit-transform: translateY(-100px);
				transform: translateY(100px);
				transition: all 500ms cubic-bezier(0.2, 1.3, 0.7, 1);
				opacity: 0;
				-webkit-appearance: none;
			}
			#button-pay:hover {
				background: #535b72;
			}
			#button-pay:active {
				-webkit-animation: cardIntro 200ms cubic-bezier(0.2, 1.3, 0.7, 1);
				animation: cardIntro 200ms cubic-bezier(0.2, 1.3, 0.7, 1);
			}
			#button-pay.show-button {
				-webkit-transform: translateY(0);
				transform: translateY(0);
				opacity: 1;
			}
			.cardinfo-card-number {
				position: relative;
			}
			#card-image {
				position: absolute;
				top: 2em;
				right: 1em;
				width: 44px;
				height: 28px;
				background-image: url();
				background-size: 86px 458px;
				border-radius: 4px;
				background-position: -100px 0;
				background-repeat: no-repeat;
				margin-bottom: 1em;
			}
			#card-image.visa {
				background-position: 0 -398px;
			}
			#card-image.master-card {
				background-position: 0 -281px;
			}
			#card-image.american-express {
				background-position: 0 -370px;
			}
			#card-image.discover {
				background-position: 0 -163px;
			}
			#card-image.maestro {
				background-position: 0 -251px;
			}
			#card-image.jcb {
				background-position: 0 -221px;
			}
			#card-image.diners-club {
				background-position: 0 -133px;
			}
			/*--------------------
				Inputs
				--------------------*/
			.input-wrapper {
				border-radius: 2px;
				background: rgba(255, 255, 255, 0.86);
				height: 2.75em;
				border: 1px solid #eee;
				box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.06);
				padding: 5px 10px;
				margin-bottom: 1em;
			}
			input{
				font-family: 'Montserrat'!important;
			}
			.cardinfo-card-number,
			.cardinfo-exp-date,
			.cardinfo-cvv {
				transition: -webkit-transform 0.3s;
				transition: transform 0.3s;
				transition: transform 0.3s, -webkit-transform 0.3s;
			}
			#form-container {
				display: block;
				width:100%
			}
			#pp-container {
				display: none;
			}
		</style>";

		echo "<script src='https://www.paypal.com/sdk/js?components=hosted-fields,buttons&client-id=".$client_ID."&currency=EUR' data-client-token='".$this->client_token()."'></script>";
		echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js'></script>";

		$createOrder = $url.'v2/checkout/orders/';
		if ($this->wire('user')->language) {
			$lang = $this->wire('user')->language;
			$landPath = $lang->name;
		} else {
			$landPath = '';
		}
		if ($landPath == 'default') {
			$landPath = 'en';
		}
		$capture = 'https://'.$_SERVER['HTTP_HOST'].'/'.$landPath.'/'.$this->capture.'/';
		$successUrl = 'https://'.$_SERVER['HTTP_HOST'].'/'.$landPath.'/'.$this->successUrl.'/';

		// Take Order information
		$order_id=$this->id;
		$order=$this->getOrder($order_id);

		$data = '
		let data =
			{
				"intent": "CAPTURE",
				"payer":{
					"name":{
						"given_name": "'.$order->pad_firstname.'",
						"surname": "'.$order->pad_lastname.'"
					},
					"email_address": "'.$order->email.'",
					"phone":{
						"phone_type": "MOBILE",
						"phone_number":{
							"national_number": "'.str_replace("+", "", $order->pad_phone).'"
						}
					},
					"address":{
						"address_line_1": "'.$order->pad_address.'",
						"address_line_2": "",
						"admin_area_1": "'.$order->pad_city.'",
						"admin_area_2": "'.$order->pad_city.'",
						"postal_code": "'.$order->pad_postcode.'",
						"country_code": "'.$order->pad_countrycode.'"
					}
				},
				"purchase_units": [{
					"reference_id": "'.$order->id.'",
					"description": "Numero di ordine: '.$order->id.'",
					"custom_id": "'.$order->id.'",
					"invoice_id":  "'.$order->id.'",
					"soft_descriptor": "PlayWood.it",
					"amount": {
						"currency_code": "EUR",
						"value": "'.$this->totalAmont().'",
						"breakdown": {
						  "item_total": {
							  "currency_code": "EUR",
							  "value": "'.$this->totalAmont().'"
							}
						}
					},
					"shipping":{
						"name":{
							"full_name": "'.$order->pad_firstname.' '.$order->pad_lastname.'"
						},
						"address":{
							"address_line_1": "'.$order->pad_address.'",
							"address_line_2": "",
							"admin_area_2": "'.$order->pad_city.'",
							"admin_area_1": "'.$order->pad_city.'",
							"postal_code": "'.$order->pad_postcode.'",
							"country_code": "'.$order->pad_countrycode.'"
						}
					}
				}],
				"application_context":{
					"shipping_preference":"SET_PROVIDED_ADDRESS"
				}
			};';

		// Render HTML form Card + PayPal Button (include all PaylPal payment system)
		$out = '
		<div class="columns payment-system">
		  <div class="column col-5 col-md-12">
				<h6>Credit/Debit Card</h6>
				<div class="form-container" id="form-container">
					<div id="payments-sdk__contingency-lightbox"></div>
					<form id="card-form">
						<div class="cardinfo-card-number">
							<label class="cardinfo-label" for="card-number">Card Number</label>
							<div class="input-wrapper" id="card-number"></div>
							<div id="card-image"></div>
						</div>
						<div class="cardinfo-wrapper">
							<div class="cardinfo-exp-date">
								<label class="cardinfo-label" for="expiration-date">Valid Thru</label>
								<div class="input-wrapper" id="expiration-date"></div>
							</div>
							<div class="cardinfo-cvv">
								<label class="cardinfo-label" for="cvv">CVV</label>
								<div class="input-wrapper" id="cvv"></div>
							</div>
						</div>
						<input id="button-pay" type="submit"  class="show-button" value="Pay" />
					</form>
				</div>
		  </div>
		  <div class="divider-vert hide-md" data-content="OR" style="padding: 0.8rem 2rem"></div>
		  <div class="column col-5 col-md-12">
				<!-- PayPal Button -->
				<div class="pp-container">
					<h6>PayPal</h6>
					<div style="margin:10px 0 0 0;text-align:center;" id="paypal-button-container"></div>
						<!-- The div that is replaced with the button -->
				</div>
		  </div>
			<div class="column col-12">
				<div class="results" id="results">
					<div id="labelresult" ></div>
				</div>
			</div>
		</div>';

		$out .= "<script>
			".$data."
			var form = document.querySelector('#card-form');
			var o ;

			if (paypal.HostedFields.isEligible() === true) {
				paypal.HostedFields.render({
					createOrder: () => {
						// logic to return the order ID from PayPal
						return fetch('".$createOrder."', {
							method: 'post',
							headers: {
								'Accept': 'application/json',
								'Content-Type': 'application/json',
								'Authorization': 'Bearer ".$this->access_token()."'
							},
							body: JSON.stringify(data),
						})
						.then(function(res) {
							return res.json();
						})
						.then(function(data) {
							console.log(data);
							return data.id;
						})
					},
					styles: {
						'input': {
							'font-size': '14px',
							'font-family': 'Product Sans',
							'color': '#3a3a3a'
						},
						// Style the text of an invalid input
						'input.invalid': {
							'color': '#E53A40'
						},
					},
					fields: {
						number: {
							selector: '#card-number',
							placeholder: 'Credit Card Number',
						},
						cvv: {
							selector: '#cvv',
							placeholder: 'CVV',
						},
						expirationDate: {
							selector: '#expiration-date',
							placeholder: 'MM/YY',
						}
					}
				})
				.then((hostedFields) => {
					hostedFields.on('validityChange', function (event) {
						console.log('CCF Event \"validityChange\", state='+hostedFields.getState() + \",event=\" + event);
							// Check if all fields are valid, then show submit button
							var formValid = Object.keys(event.fields).every(function (key) {
							return event.fields[key].isValid;
						});
						if (formValid) {
								$('#button-pay').addClass('show-button');
						} else {
								$('#button-pay').removeClass('show-button');
						}
					});
					var cvvLabel = document.querySelector('label[for=\"cvv\"]'); // The label for your CVV field
					hostedFields.on('cardTypeChange', function (event) {
						console.log('CCF Event \"cardTypeChange\", state='+hostedFields.getState() + \",event=\" + event);
						console.log( event);

						// Change card bg depending on card type
						if (event.cards.length === 1) {
							$(form).removeClass().addClass(event.cards[0].type);
							$('#card-image').removeClass().addClass(event.cards[0].type);
							console.log('CCF Card Type '+ event.cards[0].niceType);

							// Change the CVV length for AmericanExpress cards
							if (event.cards[0].code.size === 4) {
								hostedFields.setAttribute({
									field: 'cvv',
									attribute: 'placeholder',
									value: '1234'
								});
							}
						} else {
							hostedFields.setAttribute({
								field: 'cvv',
								attribute: 'placeholder',
								value: '123'
							});
						}
					});
					document.querySelector('#card-form').addEventListener('submit', (event) => {
						window.onerror = function (msg, url, line) {
							document.querySelector('#messagePayment').innerHTML = '". __('Payment error') ."';
							document.querySelector('#successful').innerHTML = '". __('Please check the data entered or contact our customer service') ."';
							document.querySelector('.empty').style.display = 'none';
							document.querySelector('#modal-id-payment-check').classList.add('active');
            }
						event.preventDefault();
						hostedFields.submit({
							// Need to specify when triggering 3D Secure authentication
							contingencies: ['3D_SECURE']  }).then(payload => {
							console.log('payload --',payload);

							const data = { id: payload.orderId };

							return fetch('".$capture."', {
								method: 'post',
								mode: 'cors',
								headers: {
									'Accept': 'application/json',
									'Content-Type': 'application/json',
								},
								body: JSON.stringify(data)
							})
							.then(function(res) {
								return res.json();
							})
							.then(function(data) {
									console.log(data);
									var paymentStatus = data.purchase_units[0].payments.captures[0].status;
									console.log(paymentStatus);
									if (paymentStatus == 'COMPLETED') {
										document.querySelector('#messagePayment').innerHTML = '". __('Payment successful') ."';
										document.querySelector('#successful').innerHTML = '<p>". __('Very soon you will be redirected to the confirmation page. If this does not happen within a few seconds, please click the button') ." </p><a class=\'btn btn-primary\' href=" . $successUrl . ">".__('Go to confermation page')."</a>';
										document.querySelector('.empty').style.display = 'none';
										document.querySelector('#modal-id-payment-check').classList.add('active');
										setTimeout(function(){ window.location.href = '" . $successUrl . "' }, 1000);
									}
									if (paymentStatus == 'DECLINED') {
										var paymentStatusError = data.purchase_units[0].payments.captures[0].processor_response.response_code;
										switch (paymentStatusError) {
											case '5120':
												var errorType = '". __('Insufficient funds') ."';
												break;
											case '5100':
												var errorType = '". __('Please check the data entered') ."';
												break;
											case '5110':
												var errorType = '". __('CVV2 verification failed') ."';
												break;
											case '5140':
												var errorType = '". __('Card was closed') ."';
												break;
											case '5400':
												var errorType = '". __('The card has expired') ."';
												break;
											case '9540':
												var errorType = '". __('Card refused') ."';
												break;
											default:
												var errorType = '". __('Unrecognized error number: ') ."'+paymentStatusError;
												break;
										}
										document.querySelector('#messagePayment').innerHTML = '". __('Payment error') ."';
										document.querySelector('#successful').innerHTML = errorType;
										document.querySelector('.empty').style.display = 'none';
										document.querySelector('#modal-id-payment-check').classList.add('active');
									}
									return data.id;
							})
							.catch(function(err) {
								document.querySelector('#messagePayment').innerHTML = '". __('Payment error') ."';
								document.querySelector('#successful').innerHTML = '". __('Please check the data entered or contact our customer service') ."';
								document.querySelector('.empty').style.display = 'none';
								document.querySelector('#modal-id-payment-check').classList.add('active');
								console.log(err);
						  })
						})
					})
				})
			};

			//////////////////////PayPal button
			paypal.Buttons({
				createOrder: () => {
					// logic to return an order ID from your server
					return fetch('".$createOrder."', {
						method: 'post',
						headers: {
							'Accept': 'application/json',
							'Content-Type': 'application/json',
				      'Authorization': 'Bearer ".$this->access_token()."'
						},
						body: JSON.stringify(data)
					})
					.then(function(res) {
						console.log(res);
						return res.json();
					})
					.then(function(data) {
						console.log(data);
						return data.id;
					});
				},

				onApprove: function(data, actions) {
					console.log('data:',data);

					urlPay = 'https://api-m.paypal.com/v2/checkout/orders/'+data.orderID+'/capture';

					return fetch(urlPay, {
						method: 'post',
						headers: {
							'Content-Type': 'application/json',
				      'Authorization': 'Bearer ".$this->access_token()."'
						},
					})
					.then(function(res) {
						return res.json();
					}).then(function(data) {
						console.log(data);
						document.querySelector('#messagePayment').innerHTML = '". __('Payment successful') ."';
						document.querySelector('#successful').innerHTML = '<p>". __('Very soon you will be redirected to the confirmation page. If this does not happen within a few seconds, please click the button') ." </p><a class=\'btn btn-primary\' href=" . $successUrl . ">".__('Go to confermation page')."</a>';
						document.querySelector('.empty').style.display = 'none';
						document.querySelector('#modal-id-payment-check').classList.add('active');
						setTimeout(function(){ window.location.href = '" . $successUrl . "' }, 1500);

						return data.id;
					});
				}
			}).render('#paypal-button-container');
			/////////////////////////////////
		</script>";

		return $out;
	}

	private function getOrder($order_id) {
		$order=wire('pages')->get($order_id);
		if( !$order || !$order instanceof PadOrder) {
			return false;
		}
		return $order;
	}

	public static function getModuleConfigInputfields(array $dataBK) {

		$inputfields=new InputfieldWrapper();
		$modules=wire('modules');

		$requiredFields=$modules->get("InputfieldFieldset");
		$requiredFields->label='Required Fields';

		$f=$modules->get('InputfieldRadios');
		$f->name='enviroment';
		$f->label='Enviroment';
		$f->required=true;
		$f->columnWidth=100;
		$f->addOption('sandbox', 'Sandbox');
		$f->addOption('production', 'Live');
		$f->value=isset($dataBK['enviroment']) ? $dataBK['enviroment']: 'live';
		$inputfields->add($f);

		$f=$modules->get('InputfieldText');
		$f->name='clientIdSandbox';
		$f->label="Sandbox Client ID";
		$f->notes="Get your Sandbox Client ID by creating a REST API app [here](https://developer.paypal.com/developer/applications/create).";
		$f->required=true;
		$f->columnWidth=50;
		if(isset($dataBK['clientIdSandbox'])) $f->value=$dataBK['clientIdSandbox'];
		$inputfields->add($f);

		$f=$modules->get('InputfieldText');
		$f->name='clientIdLive';
		$f->label="Live Client ID";
		$f->notes="Get your Live Client ID by creating a REST API app [here](https://developer.paypal.com/developer/applications/create).";
		$f->required=true;
		$f->columnWidth=50;
		if(isset($dataBK['clientIdLive'])) $f->value=$dataBK['clientIdLive'];
		$inputfields->add($f);

		$f=$modules->get('InputfieldText');
		$f->name='secretCodeSandbox';
		$f->label="SECRET CODE Sandbox";
		$f->notes="Get your SECRET CODE somewhere";
		$f->required=true;
		$f->columnWidth=50;
		if(isset($dataBK['secretCodeSandbox'])) $f->value=$dataBK['secretCodeSandbox'];
		$inputfields->add($f);

		$f=$modules->get('InputfieldText');
		$f->name='secretCodeLive';
		$f->label="SECRET CODE Live";
		$f->notes="Get your SECRET CODE somewhere";
		$f->required=true;
		$f->columnWidth=50;
		if(isset($dataBK['secretCodeLive'])) $f->value=$dataBK['secretCodeLive'];
		$inputfields->add($f);

		$f=$modules->get('InputfieldText');
		$f->name='capture';
		$f->label="Capture Page";
		$f->notes="Path of the URL, like capture-order";
		$f->required=true;
		$f->columnWidth=50;
		if(isset($dataBK['capture'])) $f->value=$dataBK['capture'];
		$inputfields->add($f);

		$f=$modules->get('InputfieldText');
		$f->name='successUrl';
		$f->label="Your success Page";
		$f->notes="URL of the success page, like: checkout/success";
		$f->required=true;
		$f->columnWidth=50;
		if(isset($dataBK['successUrl'])) $f->value=$dataBK['successUrl'];
		$inputfields->add($f);

		return $inputfields;
	}

}


//POPUP TO ADD IN CONFERMATION
<!-- <div class="modal" id="modal-id-payment-check">
  <div class="modal-container">
		<div class="modal-header">
			<a rel="nofollow, noindex" class="btn btn-clear float-right close-modal"></a>
		</div>
    <div class="modal-body">
      <div class="content text-center">
        <h3 id="messagePayment"></h3>
				<div id="successful"></div>
      </div>
    </div>
		<div class="modal-footer text-center">
			<span style="color:gray">Thank you</span>
		</div>
  </div>
</div> -->


